name: Update Bangladesh Health Database

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: write

jobs:
  update:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: |
          pip install requests beautifulsoup4

      - name: Collect DGHS data
        run: |
          python collector.py

      - name: Save database
        run: |
          git config user.name "Health Database Bot"
          git config user.email "actions@github.com"

          git add data/health-data.json

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto update health database"
            git push
          fi
